using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Aura3DRobotConverter.Models;

namespace Aura3DRobotConverter.Services
{
    /// <summary>
    /// URDF RobotConfig → USDA 변환기
    /// 지원: box/cylinder/sphere 프리미티브, 조인트 트랜스폼,
    ///       비주얼 오리진, UsdPreviewSurface 머티리얼,
    ///       USD Physics (PhysicsArticulationRootAPI, PhysicsRevoluteJoint 등)
    /// </summary>
    public static class UsdaFromUrdfExporter
    {
        // ── 공개 진입점 ──────────────────────────────────────────────────────
        public static string Export(RobotConfig config)
        {
            var sb = new StringBuilder();
            string robotName = Safe(config.RobotName ?? "AuraRobot");

            // 조인트 맵: child → joint (어떤 조인트가 이 링크를 자식으로 갖는가)
            var childJointMap = config.Joints.ToDictionary(j => j.Child, j => j);

            // ── 헤더 ──────────────────────────────────────────────────────────
            sb.AppendLine("#usda 1.0");
            sb.AppendLine("(");
            sb.AppendLine($"    defaultPrim = \"{robotName}\"");
            sb.AppendLine("    upAxis = \"Z\"");
            sb.AppendLine("    metersPerUnit = 1.0");
            sb.AppendLine($"    doc = \"Generated by Aura3D Robot CAD Converter from {config.RobotName}.urdf\"");
            sb.AppendLine(")");
            sb.AppendLine();

            // ── 루트 Xform ───────────────────────────────────────────────────
            sb.AppendLine($"def Xform \"{robotName}\" (");
            sb.AppendLine("    kind = \"component\"");
            sb.AppendLine("    apiSchemas = [\"PhysicsArticulationRootAPI\"]");
            sb.AppendLine(")");
            sb.AppendLine("{");

            // ── 머티리얼 모음 ─────────────────────────────────────────────────
            sb.AppendLine("    def Scope \"Looks\"");
            sb.AppendLine("    {");
            var materialNames = WriteMaterials(sb, config.Links, robotName);
            sb.AppendLine("    }");
            sb.AppendLine();

            // ── 링크 Xform (루트 레벨, 조인트 트랜스폼 포함) ─────────────────
            foreach (var link in config.Links)
            {
                string linkName = Safe(link.Name);
                bool hasJoint = childJointMap.TryGetValue(link.Name, out var parentJoint);

                sb.AppendLine($"    def Xform \"{linkName}\" (");
                sb.AppendLine("        apiSchemas = [\"PhysicsMassAPI\", \"PhysicsRigidBodyAPI\"]");
                sb.AppendLine("    )");
                sb.AppendLine("    {");

                // 질량/관성
                sb.AppendLine($"        float physics:mass = {link.Mass:F4}");
                var com = link.CenterOfMass;
                sb.AppendLine($"        point3f physics:centerOfMass = ({com[0]:F6}, {com[1]:F6}, {com[2]:F6})");

                // ─ 조인트 트랜스폼 (부모 좌표계 기준) ─────────────────────────
                if (hasJoint && parentJoint != null)
                {
                    var jxyz = parentJoint.Origin.Xyz;
                    var jrpy = parentJoint.Origin.Rpy;
                    bool hasTrans = jxyz.Any(v => Math.Abs(v) > 1e-9);
                    bool hasRot   = jrpy.Any(v => Math.Abs(v) > 1e-9);

                    var ops = new List<string>();
                    if (hasTrans)
                    {
                        sb.AppendLine($"        double3 xformOp:translate = ({jxyz[0]:F6}, {jxyz[1]:F6}, {jxyz[2]:F6})");
                        ops.Add("\"xformOp:translate\"");
                    }
                    if (hasRot)
                    {
                        double rx = jrpy[0] * 180.0 / Math.PI;
                        double ry = jrpy[1] * 180.0 / Math.PI;
                        double rz = jrpy[2] * 180.0 / Math.PI;
                        sb.AppendLine($"        double3 xformOp:rotateXYZ = ({rx:F4}, {ry:F4}, {rz:F4})");
                        ops.Add("\"xformOp:rotateXYZ\"");
                    }
                    if (ops.Count > 0)
                        sb.AppendLine($"        uniform token[] xformOpOrder = [{string.Join(", ", ops)}]");
                }

                // ─ 비주얼 + 지오메트리 ──────────────────────────────────────
                if (!string.IsNullOrEmpty(link.PrimitiveType))
                {
                    sb.AppendLine($"        def Xform \"visual\"");
                    sb.AppendLine("        {");

                    // 비주얼 오리진 트랜스폼
                    var vxyz = link.VisualOriginXyz;
                    var vrpy = link.VisualOriginRpy;
                    bool vHasTrans = vxyz.Any(v => Math.Abs(v) > 1e-9);
                    bool vHasRot   = vrpy.Any(v => Math.Abs(v) > 1e-9);
                    var vops = new List<string>();
                    if (vHasTrans)
                    {
                        sb.AppendLine($"            double3 xformOp:translate = ({vxyz[0]:F6}, {vxyz[1]:F6}, {vxyz[2]:F6})");
                        vops.Add("\"xformOp:translate\"");
                    }
                    if (vHasRot)
                    {
                        double rx = vrpy[0] * 180.0 / Math.PI;
                        double ry = vrpy[1] * 180.0 / Math.PI;
                        double rz = vrpy[2] * 180.0 / Math.PI;
                        sb.AppendLine($"            double3 xformOp:rotateXYZ = ({rx:F4}, {ry:F4}, {rz:F4})");
                        vops.Add("\"xformOp:rotateXYZ\"");
                    }
                    if (vops.Count > 0)
                        sb.AppendLine($"            uniform token[] xformOpOrder = [{string.Join(", ", vops)}]");

                    // 머티리얼 바인딩
                    string matName = materialNames.TryGetValue(link.Name, out var mn) ? mn : "M_default";

                    // 프리미티브 지오메트리
                    WriteGeometry(sb, link, robotName, matName);
                    sb.AppendLine("        }"); // visual
                }
                else if (!string.IsNullOrEmpty(link.MeshPath))
                {
                    sb.AppendLine($"        def Xform \"visual_mesh\"");
                    sb.AppendLine("        (");
                    sb.AppendLine($"            prepend references = @./{link.MeshPath}@");
                    sb.AppendLine("        )");
                    sb.AppendLine("        {");
                    sb.AppendLine("        }");
                }

                sb.AppendLine("    }"); // link
                sb.AppendLine();
            }

            // ── 조인트 Physics ────────────────────────────────────────────────
            foreach (var joint in config.Joints)
            {
                string jointName = Safe(joint.Name);
                string parentName = Safe(joint.Parent);
                string childName  = Safe(joint.Child);

                string usdJointType = joint.Type switch
                {
                    "revolute"   => "PhysicsRevoluteJoint",
                    "continuous" => "PhysicsRevoluteJoint",
                    "prismatic"  => "PhysicsPrismaticJoint",
                    _            => "PhysicsFixedJoint"
                };

                sb.AppendLine($"    def {usdJointType} \"{jointName}\"");
                sb.AppendLine("    {");
                sb.AppendLine($"        rel physics:body0 = </{robotName}/{parentName}>");
                sb.AppendLine($"        rel physics:body1 = </{robotName}/{childName}>");

                // 조인트 위치 (body0 프레임 기준)
                var xyz = joint.Origin.Xyz;
                var rpy = joint.Origin.Rpy;
                sb.AppendLine($"        point3f physics:localPos0 = ({xyz[0]:F6}, {xyz[1]:F6}, {xyz[2]:F6})");

                // RPY → 쿼터니언 (body0 프레임)
                var (qw, qx, qy, qz) = RpyToQuat(rpy[0], rpy[1], rpy[2]);
                sb.AppendLine($"        quatf physics:localRot0 = ({qw:F6}, {qx:F6}, {qy:F6}, {qz:F6})");
                sb.AppendLine("        point3f physics:localPos1 = (0.0, 0.0, 0.0)");
                sb.AppendLine("        quatf physics:localRot1 = (1.0, 0.0, 0.0, 0.0)");

                if (usdJointType == "PhysicsRevoluteJoint" || usdJointType == "PhysicsPrismaticJoint")
                {
                    var axis = joint.Axis;
                    string axisToken = "Z";
                    if (Math.Abs(axis[0]) > 0.9) axisToken = "X";
                    else if (Math.Abs(axis[1]) > 0.9) axisToken = "Y";
                    sb.AppendLine($"        token physics:axis = \"{axisToken}\"");

                    if (usdJointType == "PhysicsRevoluteJoint")
                    {
                        if (joint.Type == "continuous")
                        {
                            // continuous → 무한 회전 (lowerLimit > upperLimit)
                            sb.AppendLine("        float physics:lowerLimit = 1.0");
                            sb.AppendLine("        float physics:upperLimit = -1.0");
                        }
                        else
                        {
                            double lo = joint.Limits.Lower * 180.0 / Math.PI;
                            double hi = joint.Limits.Upper * 180.0 / Math.PI;
                            sb.AppendLine($"        float physics:lowerLimit = {lo:F4}");
                            sb.AppendLine($"        float physics:upperLimit = {hi:F4}");
                        }
                        sb.AppendLine($"        float physics:maxForce = {joint.Limits.Effort:F2}");
                        sb.AppendLine($"        float physics:maxVelocity = {joint.Limits.Velocity:F2}");
                    }
                    else
                    {
                        sb.AppendLine($"        float physics:lowerLimit = {joint.Limits.Lower:F4}");
                        sb.AppendLine($"        float physics:upperLimit = {joint.Limits.Upper:F4}");
                    }
                }

                sb.AppendLine("    }"); // joint
                sb.AppendLine();
            }

            sb.AppendLine("}"); // robotName
            return sb.ToString();
        }

        // ── 머티리얼 출력 ─────────────────────────────────────────────────────
        private static Dictionary<string, string> WriteMaterials(
            StringBuilder sb, List<RobotLink> links, string robotName)
        {
            var result = new Dictionary<string, string>();
            var seen   = new Dictionary<string, string>(); // colorKey → matName

            // default material
            sb.AppendLine("        def Material \"M_default\"");
            sb.AppendLine("        {");
            WritePbrShader(sb, 0.8f, 0.8f, 0.8f, $"/{robotName}/Looks/M_default");
            sb.AppendLine("        }");

            foreach (var link in links)
            {
                float r = 0.8f, g = 0.8f, b = 0.8f;
                if (link.ColorRgba is { Length: >= 3 })
                {
                    r = link.ColorRgba[0];
                    g = link.ColorRgba[1];
                    b = link.ColorRgba[2];
                }
                string key  = $"{r:F3}_{g:F3}_{b:F3}";
                if (!seen.TryGetValue(key, out string? matName))
                {
                    matName = $"M_{Safe(link.Name)}";
                    seen[key] = matName;
                    sb.AppendLine($"        def Material \"{matName}\"");
                    sb.AppendLine("        {");
                    WritePbrShader(sb, r, g, b, $"/{robotName}/Looks/{matName}");
                    sb.AppendLine("        }");
                }
                result[link.Name] = matName;
            }
            return result;
        }

        private static void WritePbrShader(StringBuilder sb, float r, float g, float b, string matPath)
        {
            sb.AppendLine($"            token outputs:surface.connect = <{matPath}/Shader.outputs:surface>");
            sb.AppendLine("            def Shader \"Shader\"");
            sb.AppendLine("            {");
            sb.AppendLine("                uniform token info:id = \"UsdPreviewSurface\"");
            sb.AppendLine($"                color3f inputs:diffuseColor = ({r:F4}, {g:F4}, {b:F4})");
            sb.AppendLine("                float inputs:roughness = 0.5");
            sb.AppendLine("                float inputs:metallic = 0.05");
            sb.AppendLine("                token outputs:surface");
            sb.AppendLine("            }");
        }

        // ── 지오메트리 출력 ───────────────────────────────────────────────────
        private static void WriteGeometry(StringBuilder sb, RobotLink link,
                                          string robotName, string matName)
        {
            string pt  = (link.PrimitiveType ?? "box").ToLower();
            var    pp  = link.PrimitiveParams ?? Array.Empty<double>();
            string matPath = $"/{robotName}/Looks/{matName}";

            switch (pt)
            {
                case "box":
                {
                    // params: [size_x, size_y, size_z]
                    double hx = (pp.Length > 0 ? pp[0] : 1.0) / 2.0;
                    double hy = (pp.Length > 1 ? pp[1] : 1.0) / 2.0;
                    double hz = (pp.Length > 2 ? pp[2] : 1.0) / 2.0;
                    sb.AppendLine("            def Cube \"geom\"");
                    sb.AppendLine("            {");
                    // USD Cube: 기본 크기 [-1,1]^3 → scale로 half-extent 지정
                    sb.AppendLine($"                double3 xformOp:scale = ({hx:F6}, {hy:F6}, {hz:F6})");
                    sb.AppendLine("                uniform token[] xformOpOrder = [\"xformOp:scale\"]");
                    sb.AppendLine($"                float3[] extent = [(-1, -1, -1), (1, 1, 1)]");
                    sb.AppendLine($"                rel material:binding = <{matPath}>");
                    sb.AppendLine("            }");
                    break;
                }
                case "cylinder":
                {
                    // params: [length, radius]  (URDF: length = height along Z)
                    double length = pp.Length > 0 ? pp[0] : 1.0;
                    double radius = pp.Length > 1 ? pp[1] : 0.5;
                    sb.AppendLine("            def Cylinder \"geom\"");
                    sb.AppendLine("            {");
                    // USD Cylinder: 기본 축 = Y, height=2, radius=1
                    // URDF visual origin rpy=(π/2,0,0) 이 이미 상위 visual Xform에 적용됨
                    sb.AppendLine($"                double height = {length:F6}");
                    sb.AppendLine($"                double radius = {radius:F6}");
                    sb.AppendLine("                token axis = \"Z\"");
                    sb.AppendLine($"                float3[] extent = [({-radius:F6}, {-radius:F6}, {-length/2:F6}), ({radius:F6}, {radius:F6}, {length/2:F6})]");
                    sb.AppendLine($"                rel material:binding = <{matPath}>");
                    sb.AppendLine("            }");
                    break;
                }
                case "sphere":
                {
                    double radius = pp.Length > 0 ? pp[0] : 0.5;
                    sb.AppendLine("            def Sphere \"geom\"");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                double radius = {radius:F6}");
                    sb.AppendLine($"                float3[] extent = [({-radius:F6}, {-radius:F6}, {-radius:F6}), ({radius:F6}, {radius:F6}, {radius:F6})]");
                    sb.AppendLine($"                rel material:binding = <{matPath}>");
                    sb.AppendLine("            }");
                    break;
                }
                default:
                {
                    sb.AppendLine($"            # unsupported primitive: {pt}");
                    break;
                }
            }
        }

        // ── RPY → 쿼터니언 (w, x, y, z) ──────────────────────────────────────
        private static (double w, double x, double y, double z) RpyToQuat(double r, double p, double y)
        {
            double cr = Math.Cos(r / 2), sr = Math.Sin(r / 2);
            double cp = Math.Cos(p / 2), sp = Math.Sin(p / 2);
            double cy = Math.Cos(y / 2), sy = Math.Sin(y / 2);

            double qw = cr * cp * cy + sr * sp * sy;
            double qx = sr * cp * cy - cr * sp * sy;
            double qy = cr * sp * cy + sr * cp * sy;
            double qz = cr * cp * sy - sr * sp * cy;
            return (qw, qx, qy, qz);
        }

        // ── USD 식별자 안전 변환 ───────────────────────────────────────────────
        private static string Safe(string name) =>
            System.Text.RegularExpressions.Regex.Replace(name, "[^A-Za-z0-9_]", "_");
    }
}
